let music_i_wish_we_are_alone_in_the_universe = {
    "rowLen": 6615,
    "endPattern": 27,
    "songData": [
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 180,
            "osc1_waveform": 0,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 9,
            "osc2_xenv": 0,
            "osc2_vol": 116,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 197,
            "env_sustain": 88,
            "env_release": 10614,
            "env_master": 45,
            "fx_filter": 0,
            "fx_freq": 11025,
            "fx_resonance": 255,
            "fx_delay_time": 2,
            "fx_delay_amt": 146,
            "fx_pan_freq": 3,
            "fx_pan_amt": 47,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        145,
                        145,
                        0,
                        150,
                        150,
                        0,
                        153,
                        153,
                        0,
                        150,
                        150,
                        0,
                        0,
                        0,
                        0,
                        0,
                        145,
                        145,
                        0,
                        0,
                        150,
                        150,
                        0,
                        153,
                        153,
                        0,
                        152,
                        152,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 4,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 223,
            "osc1_waveform": 3,
            "osc2_oct": 4,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 240,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 100,
            "env_sustain": 10909,
            "env_release": 1234,
            "env_master": 162,
            "fx_filter": 2,
            "fx_freq": 11024,
            "fx_resonance": 240,
            "fx_delay_time": 6,
            "fx_delay_amt": 57,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 7,
            "lfo_amt": 80,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                4,
                1,
                2,
                3,
                2,
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                2
            ],
            "c": [
                {
                    "n": [
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0,
                        157,
                        0
                    ]
                },
                {
                    "n": [
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0,
                        162,
                        0
                    ]
                },
                {
                    "n": [
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0
                    ]
                },
                {
                    "n": [
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        169,
                        0,
                        167,
                        0,
                        167,
                        0,
                        167,
                        0,
                        167,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0,
                        165,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 183,
            "osc1_waveform": 2,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 18,
            "osc2_xenv": 0,
            "osc2_vol": 140,
            "osc2_waveform": 2,
            "noise_fader": 0,
            "env_attack": 100000,
            "env_sustain": 56363,
            "env_release": 100000,
            "env_master": 199,
            "fx_filter": 2,
            "fx_freq": 200,
            "fx_resonance": 254,
            "fx_delay_time": 8,
            "fx_delay_amt": 24,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 0,
            "lfo_waveform": 0,
            "p": [
                2,
                3,
                4,
                3,
                2,
                3,
                4,
                5,
                2,
                3,
                4,
                3,
                2,
                3,
                4,
                5,
                2,
                3,
                4,
                3,
                2,
                3,
                4,
                5,
                3,
                6
            ],
            "c": [
                {
                    "n": [
                        121,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        121,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        121,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        121,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        126,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        126,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        129,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        129,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        133,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        131,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        129,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 218,
            "osc1_waveform": 0,
            "osc2_oct": 7,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 227,
            "osc2_waveform": 0,
            "noise_fader": 0,
            "env_attack": 444,
            "env_sustain": 548,
            "env_release": 8772,
            "env_master": 93,
            "fx_filter": 2,
            "fx_freq": 1052,
            "fx_resonance": 243,
            "fx_delay_time": 7,
            "fx_delay_amt": 32,
            "fx_pan_freq": 7,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 0,
            "lfo_amt": 67,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        134,
                        0,
                        0,
                        0,
                        134,
                        0,
                        134,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0,
                        134,
                        0,
                        0,
                        0,
                        134,
                        0,
                        134,
                        0,
                        0,
                        0,
                        0,
                        0,
                        135,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 255,
            "osc1_waveform": 3,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 255,
            "osc2_waveform": 1,
            "noise_fader": 45,
            "env_attack": 140347,
            "env_sustain": 13706,
            "env_release": 94082,
            "env_master": 35,
            "fx_filter": 3,
            "fx_freq": 200,
            "fx_resonance": 188,
            "fx_delay_time": 8,
            "fx_delay_amt": 24,
            "fx_pan_freq": 0,
            "fx_pan_amt": 167,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 14,
            "lfo_amt": 43,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                4,
                1
            ],
            "c": [
                {
                    "n": [
                        133,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        138,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        141,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        133,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        143,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        141,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 7,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 0,
            "osc1_vol": 23,
            "osc1_waveform": 1,
            "osc2_oct": 6,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 0,
            "osc2_vol": 192,
            "osc2_waveform": 3,
            "noise_fader": 0,
            "env_attack": 200,
            "env_sustain": 137,
            "env_release": 1776,
            "env_master": 192,
            "fx_filter": 4,
            "fx_freq": 2235,
            "fx_resonance": 222,
            "fx_delay_time": 4,
            "fx_delay_amt": 125,
            "fx_pan_freq": 0,
            "fx_pan_amt": 0,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 0,
            "lfo_freq": 0,
            "lfo_amt": 116,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                2,
                3,
                4,
                1,
                2,
                3,
                2,
                1,
                2,
                3,
                4
            ],
            "c": [
                {
                    "n": [
                        157,
                        0,
                        0,
                        0,
                        0,
                        0,
                        157,
                        0,
                        160,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        162,
                        0,
                        0,
                        0,
                        0,
                        0,
                        162,
                        0,
                        164,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        165,
                        0,
                        0,
                        0,
                        0,
                        0,
                        167,
                        0,
                        164,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    "n": [
                        157,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        167,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        165,
                        0,
                        0,
                        0,
                        164,
                        0,
                        0,
                        0
                    ]
                }
            ]
        },
        {
            "osc1_oct": 6,
            "osc1_det": 0,
            "osc1_detune": 0,
            "osc1_xenv": 1,
            "osc1_vol": 160,
            "osc1_waveform": 0,
            "osc2_oct": 8,
            "osc2_det": 0,
            "osc2_detune": 0,
            "osc2_xenv": 1,
            "osc2_vol": 160,
            "osc2_waveform": 0,
            "noise_fader": 127,
            "env_attack": 50,
            "env_sustain": 200,
            "env_release": 6800,
            "env_master": 55,
            "fx_filter": 4,
            "fx_freq": 11025,
            "fx_resonance": 254,
            "fx_delay_time": 6,
            "fx_delay_amt": 32,
            "fx_pan_freq": 5,
            "fx_pan_amt": 61,
            "lfo_osc1_freq": 0,
            "lfo_fx_freq": 1,
            "lfo_freq": 4,
            "lfo_amt": 60,
            "lfo_waveform": 0,
            "p": [
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                1,
                1,
                1,
                1
            ],
            "c": [
                {
                    "n": [
                        0,
                        0,
                        139,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        139,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        139,
                        0,
                        0,
                        0,
                        0,
                        0,
                        142,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                }
            ]
        }
    ],
    "songLen": 131
};